version: "3.5"
services:
  serverless:
    build: .
    tty: true
    stdin_open: true
    image: serverless
    working_dir: /app
    volumes:
      - .:/app
    container_name: serverless
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
